# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/lucasmbrown/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--ignore-init-module-imports",
            "--remove-unused-variables",
            "--remove-duplicate-keys",
          ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args:
          ["--keep-runtime-typing", "--py3-plus", "--py36-plus", "--py37-plus"]
  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa
        additional_dependencies: &flake8deps
          - flake8-assertive==1.3.0
          - flake8-blind-except==0.2.0
          - flake8-bandit==2.1.2
          - flake8-builtins==1.5.3
          - flake8-comprehensions==3.7.0
          # - flake8-docstrings==1.6.0
          - flake8-isort==4.1.1
          - flake8-logging-format==0.6.0
          - flake8-mutable==1.2.0
          - flake8-print==4.0.0
          - pep8-naming==0.12.1
          - toml==0.10.2
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies:
          - toml
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        additional_dependencies:
          - sqlalchemy-stubs==0.4
          - types-bleach==4.1.1
          - types-Markdown==3.3.6
          - types-pytz==2021.3.0
          - types-requests==2.25.11
          - types-simplejson==3.17.1
          - types-toml==0.10.1
          - types-PyYAML==6.0.0
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: *flake8deps
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
        args: ["--ini", "setup.cfg", "-l", "-x", "tests, build/lib"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: trailing-whitespace
