# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip: ['yesqa', 'no-commit-to-branch']
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
        # Extra args, only after removing flake8 and yesqa: '--extend-select', 'RUF100'
  - repo: https://github.com/lucasmbrown/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          [
            '--in-place',
            '--remove-all-unused-imports',
            '--ignore-init-module-imports',
            '--remove-unused-variables',
            '--remove-duplicate-keys',
          ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ['--keep-runtime-typing', '--py39-plus']
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        additional_dependencies: &flake8deps
          - flake8-assertive
          # - flake8-annotations
          - flake8-blind-except
          - flake8-builtins
          - flake8-comprehensions
          # - flake8-docstrings
          - flake8-isort
          - flake8-logging-format
          - flake8-mutable
          - flake8-print
          - pep8-naming
          - toml
          - tomli
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        additional_dependencies:
          - tomli
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        # warn-unused-ignores is unsafe with pre-commit, see
        # https://github.com/python/mypy/issues/2960
        args: ['--no-warn-unused-ignores', '--ignore-missing-imports']
        additional_dependencies:
          - flask
          - lxml-stubs
          - sqlalchemy
          - toml
          - types-bleach
          - types-Markdown
          - types-pytz
          - types-PyYAML
          - types-requests
          - types-toml
          - typing-extensions
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: *flake8deps
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-log-warn
  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        args: [
            '--disable=import-error',
            '-rn', # Disable full report
            '-sn', # Disable evaluation score
          ]
        additional_dependencies:
          - flask
          - sqlalchemy
          - tomli
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        language_version: python3
        args: ['-c', 'pyproject.toml']
        additional_dependencies:
          - bandit[toml]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ['--single-quote', '--trailing-comma', 'es5']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
