# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip: ['no-commit-to-branch']
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: ['--keep-runtime-typing', '--py39-plus']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        # warn-unused-ignores is unsafe with pre-commit, see
        # https://github.com/python/mypy/issues/2960
        args:
          [
            '--no-warn-unused-ignores',
            '--no-warn-redundant-casts',
            '--ignore-missing-imports',
          ]
        additional_dependencies:
          - flask
          - quart
          - lxml-stubs
          - sqlalchemy
          - toml
          - types-bleach
          - types-Markdown
          - types-pytz
          - types-PyYAML
          - types-requests
          - types-toml
          - typing-extensions
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-log-warn
  - repo: https://github.com/PyCQA/pylint
    rev: v3.2.3
    hooks:
      - id: pylint
        args: [
            '--disable=import-error',
            '-rn', # Disable full report
            '-sn', # Disable evaluation score
          ]
        additional_dependencies:
          - flask
          - quart
          - sqlalchemy
          - tomli
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        language_version: python3
        args: ['-c', 'pyproject.toml']
        additional_dependencies:
          - bandit[toml]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ['--single-quote', '--trailing-comma', 'es5']
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args:
          - --external-sources
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
