# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/lucasmbrown/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--ignore-init-module-imports', '--remove-unused-variable']
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies:
          - toml
  - repo: https://github.com/ambv/black
    rev: master
    hooks:
      - id: black
        language_version: python3.6
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: ["--ini", "setup.cfg", "-l", "-x", "tests, build/lib"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: fix-encoding-pragma
      - id: flake8
        additional_dependencies:
          - toml
          - flake8-assertive
          - flake8-bandit
          - flake8-blind-except
          - flake8-builtins
          - flake8-coding
          - flake8-comprehensions
          - flake8-isort
          - flake8-logging-format
          - flake8-mutable
          - pep8-naming
