# Default tool config file. See also setup.cfg for tools that don't yet
# support pyproject.toml.

[build-system]
requires = ['setuptools>=61', 'setuptools_scm[toml]']
build-backend = 'setuptools.build_meta'

[project]
name = 'coaster'
description = 'Coaster for Flask'
readme = 'README.rst'
requires-python = '>=3.7'
keywords = ['coaster', 'flask', 'framework', 'web', 'auth', 'sqlalchemy']
license = {file = 'LICENSE.txt'}
dynamic = ['version']
maintainers = [
  {name = 'Hasgeek', email = 'info@hasgeek.com'},
]
authors = [
  {name = 'Kiran Jonnalagadda'}
]
urls = {repository = 'https://github.com/hasgeek/coaster'}
classifiers = [
    'Programming Language :: Python',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Framework :: Flask',
    'License :: OSI Approved :: BSD License',
    'Operating System :: OS Independent',
    'Intended Audience :: Developers',
    'Development Status :: 5 - Production/Stable',
    'Topic :: Database',
    'Topic :: Software Development :: Libraries',
]
dependencies = [
  'aniso8601',
  'base58>=2.0.0',
  'bleach',
  'blinker',
  'Flask-Assets',
  'Flask-Migrate',
  'Flask-SQLAlchemy',
  'Flask>=2.0',
  'furl',
  'html5lib>=0.999999999',
  'isoweek',
  'Markdown>=3.2.0',
  'markupsafe',
  'nltk>=3.4.5',
  'PyExecJS',
  'pymdown-extensions>=8.0',
  'pytz',
  'semantic_version>=2.8.0',
  'sqlalchemy-utils',
  'SQLAlchemy>=1.4',
  'tldextract',
  'typing_extensions',
  'UgliPyJS',
  'Unidecode',
  'webassets',
  'werkzeug',
]

[tool.setuptools.dynamic]
version = {attr = 'coaster._version.__version__'}

[tool.setuptools.packages.find]
where = ['src']

[tool.black]
line-length = 88
target_version = ['py36']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | __pycache__
  | buck-out
  | build
  | dist
  | node_modules
  | funnel/assets
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
line_length = 88
order_by_type = true
use_parentheses = true
from_first = true
known_future_library = ['__future__']
known_first_party = ['coaster']
known_sqlalchemy = ['alembic', 'sqlalchemy', 'sqlalchemy_utils', 'flask_sqlalchemy']
known_flask = [
  'flask',
  'werkzeug',
  'itsdangerous',
  'wtforms',
  'webassets',
  'flask_assets',
  'flask_flatpages',
  'flask_mail',
  'flask_migrate',
  'flask_rq2'
]
default_section = 'THIRDPARTY'
sections = ['FUTURE', 'STDLIB', 'SQLALCHEMY', 'FLASK', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']

[tool.pytest.ini_options]
pythonpath = 'src'
required_plugins = [
  'pytest-env',
  'pytest-rerunfailures',
  'pytest-remotedata',
]
minversion = '6.0'
addopts = '--doctest-modules --ignore setup.py --cov-report=term-missing'
doctest_optionflags = ['ALLOW_UNICODE', 'ALLOW_BYTES']
filterwarnings = ['ignore::DeprecationWarning', 'ignore::UserWarning']
mocked-sessions = 'coaster.db.db.session'
env = ['FLASK_ENV=testing']
remote_data_strict = true

[tool.pylint.master]
load-plugins = ['pylint_pytest', 'pylint_flask_sqlalchemy']
max-parents = 10
init-hook = '''
import os, astroid.bases, pathlib
# Tell Pylint where to find packages from within tests
for path in pathlib.Path.cwd().parents:
    if (path / 'pyproject.toml').is_file():
      sys.path.insert(0, str(path / 'src'))
# Tell Pylint hybrid_property and cached_property are property-types
astroid.bases.POSSIBLE_PROPERTIES.add('hybrid_property')
astroid.bases.POSSIBLE_PROPERTIES.add('cached_property')
'''

[tool.pylint.message_control]
max-line-length = 88
disable = [
  'duplicate-code',
  'fixme',
  'invalid-name',
  'no-member',
  'unused-argument',
]

[tool.mypy]
files = '**/*.py'
exclude = 'node_modules'
plugins = ['sqlalchemy.ext.mypy.plugin']
ignore_missing_imports = true
show_error_codes = true
warn_unreachable = true
warn_unused_ignores = true
warn_redundant_casts = false
check_untyped_defs = false

[tool.bandit]
exclude_dirs = ['node_modules', 'build/lib']

[tool.bandit.assert_used]
skips = ['*/*_test.py', '*/test_*.py']
